Datasets:
  output/Intra-dataset/Pancreatic_data/Baron_Mouse:
  datafile: input/Intra-dataset/Pancreatic_data/Baron_Mouse/Filtered_MousePancreas_data.csv
  labfile: input/Intra-dataset/Pancreatic_data/Baron_Mouse/Labels.csv
  column: 1
number_of_features: 0
tools_to_run:
  - SVM 
